
import = [
  '~/.config/alacritty/tokyonight.toml',
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 15

[font.normal]
family = "DankMono Nerd Font"

[font.offset]
x = 0
y = 5


# Tmux
# [[keyboard.bindings]]
# chars = "\u0002s"
# key = "K"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u00021"
# key = "Key1"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u00022"
# key = "Key2"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u00023"
# key = "Key3"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u00024"
# key = "Key4"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u00025"
# key = "Key5"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u00026"
# key = "Key6"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u00027"
# key = "Key7"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u00028"
# key = "Key8"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u00029"
# key = "Key9"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002g"
# key = "G"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002:"
# key = "Comma"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002["
# key = "C"
# mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "\u0002,"
# key = "R"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002L"
# key = "L"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002p"
# key = "Left"
# mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "\u0002%"
# key = "D"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002\""
# key = "D"
# mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "\u0002n"
# key = "Right"
# mods = "Command|Shift"

# [[keyboard.bindings]]
# chars = "\u0002c"
# key = "T"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002e"
# key = "E"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002i"
# key = "I"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002T"
# key = "J"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002x"
# key = "W"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002z"
# key = "Z"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002\b"
# key = "Left"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002\f"
# key = "Right"
# mods = "Command"

# [[keyboard.bindings]]
# chars = """
# \u0002
# """
# key = "Down"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002\u000B"
# key = "Up"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002o"
# key = "Tab"
# mods = "Control"

# [[keyboard.bindings]]
# chars = "\u0002 "
# key = "Tab"
# mods = "Control|Shift"

# [[keyboard.bindings]]
# chars = "\u0002a"
# key = "A"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002u"
# key = "O"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002!"
# key = "B"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002{"
# key = "N"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "\u0002}"
# key = "P"
# mods = "Command"

# [[keyboard.bindings]]
# chars = "["
# key = "LBracket"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "]"
# key = "RBracket"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "@"
# key = "Key2"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "$"
# key = "Key4"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "|"
# key = "Backslash"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = '\'
# key = "Backslash"
# mods = "Alt|Shift"

# [[keyboard.bindings]]
# chars = "{"
# key = "LBracket"
# mods = "Alt|Shift"

# [[keyboard.bindings]]
# chars = "}"
# key = "RBracket"
# mods = "Alt|Shift"

# Zellij

[[keyboard.bindings]]
chars = "\u0002p}"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002t}"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002h}"
key = "M"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n}"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002o}"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002os}"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002tx}"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002tn}"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002pw}"
key = "v"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002pg}"
key = "g"
mods = "Command"

# Detach session
[[keyboard.bindings]]
chars = "\u0002od}"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002nl}"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002nh}"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002nj}"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002nk}"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002pl}"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002ph}"
key = "H"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002pj}"
key = "J"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002pk}"
key = "K"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002nH}"
key = "Right"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002nL}"
key = "Left"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002nJ}"
key = "Down"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002nK}"
key = "Up"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002tl}"
key = "Left"
mods = "control|Shift"

[[keyboard.bindings]]
chars = "\u0002th}"
key = "Right"
mods = "control|Shift"

[[keyboard.bindings]]
chars = "\u0002pr}"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002pd}"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002px}"
key = "X"
mods = "Command|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.95
option_as_alt = "OnlyRight"
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10
