#! /bin/sh

echo "deleting all .DS_Store files"
find . -name ".DS_Store" -type f -delete

echo "stowing ..."
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd
