#! /bin/sh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="yabai,ssh,lazygit,skhd,tmux,zsh,starship,helix,hammerspoon,gitmux,git,bin"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=~/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

