#! /bin/sh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="yabai,ssh,lazygit,kitty,skhd,tmux,zsh,neofetch,starship,helix,hammerspoon,gitmux,git,mybin,felix"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=~/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

