theme = "tokyonight"

[editor]
line-number = "relative"
mouse = false
auto-format = true
bufferline = "multiple"
color-modes = true

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
max-wrap = 25         # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""   # set wrap-indicator to "" to hide it


[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.insert]
C-space = "signature_help"

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
C-j = [
  'ensure_selections_forward',
  'extend_to_line_bounds',
  'extend_char_right',
  'extend_char_left',
  'delete_selection',
  'add_newline_below',
  'move_line_down',
  'replace_with_yanked',
]
C-k = [
  'ensure_selections_forward',
  'extend_to_line_bounds',
  'extend_char_right',
  'extend_char_left',
  'delete_selection',
  'move_line_up',
  'add_newline_above',
  'move_line_up',
  'replace_with_yanked',
]

[keys.normal]
C-q = ":quit"
tab = ":buffer-next"
S-tab = ":buffer-previous"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
F = "file_picker_in_current_directory"
q = ":q"
x = ":bc"
"," = ":w"
"!" = ":q!"
l = ":log-open"
o = ":reload-all"
g = ":pipe-to tmux split-window -v helix-live-grep"
B = ":pipe-to tmux split-window -v helix-git-blame"
H = ":sh helix-open-in-gh"
