# This will show the time on a 2nd line
# Add a "\" at the end of an item, if you want the next item to show on the same line
format = """
$username\
$directory\
$nodejs\
$character\
"""

[character]
success_symbol = '[  ](#9ece6a bold) '
error_symbol = '[  ](#f7768e bold) '
vicmd_symbol = '[󰕷  ](#9d7cd8 bold) '

[directory]
style = " bold"
disabled = false
truncation_length = 3
truncation_symbol = "…/"

[battery]
disabled = true

[gcloud]
disabled = true

[username]
style_user = '#e0af68 bold'
style_root = 'white bold'
format = '[$user]($style).@.'
show_always = true

[nodejs]
symbol = " "
format = '[[$symbol($version)](#9ece6a)]($style) '

