palette = "tokyonight_night"
format = """
[░▒▓](#c0caf5)\
[  ](bg:#c0caf5 fg:#16161e)\
[](bg:#9d7cd8 fg:#c0caf5)\
$directory\
[](fg:#9d7cd8 bg:#394b70)\
$nodejs\
[](fg:#394b70 bg:#212736)\
$rust\
$golang\
$php\
[ ](fg:#1d2230)\
$character\ 
"""

[directory]
style = "fg:#1f2335 bg:#9d7cd8"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394b70"
format = '[[ $symbol $branch ](fg:#7dcfff bg:#394b70)]($style)'

[git_status]
style = "bg:#394b70"
format = '[[($all_status$ahead_behind )](fg:#7dcfff bg:#394b70)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#7dcfff bg:#394b70)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#7dcfff bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#7dcfff bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#7dcfff bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
success_symbol = '[ ](bold green) '
error_symbol = '[ ](#E84D44) '
vimcmd_symbol = '[󰕷 ](bold green) '

[palettes.tokyonight_night]
red = "#f7768e"
orange = "#ff9e64"
yellow = "#e0af68"
light-green = "#9ece6a"
green = "#73daca"
turquoise = "#89ddff"
light-cyan = "#b4f9f8"
teal = "#2ac3de"
cyan = "#7dcfff"
blue = "#7aa2f7"
magenta = "#bb9af7"
white = "#c0caf5"
light-gray = "#9aa5ce"
parameters = "#cfc9c2"
comment = "#565f89"
black = "#414868"
foreground = "#a9b1d6"
foreground_highlight = "#c0caf5"
foreground_gutter = "#363b54"
background = "#1a1b26"
background_highlight = "#30374b"
background_menu = "#16161e"

