palette = "tokyonight_night"
format = """
(#c0caf5)\
(fg:#c0caf5)\
$directory\
(fg:#292e42)\
$nodejs\
(fg:#394b70)\
$rust\
$golang\
$php\
(fg:#1d2230)\
$character\ 
"""

[directory]
style = "fg:#bb9af7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = ""
format = '[[ $symbol $branch ](fg:#7dcfff)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:#7dcfff)]($style)'

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#7dcfff )]($style)'

[rust]
symbol = ""
format = '[[ $symbol ($version) ](fg:#7dcfff)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:#7dcfff )]($style)'

[php]
symbol = ""
format = '[[ $symbol ($version) ](fg:#7dcfff ($style)'

[time]
disabled = false
time_format = "%R"                           # Hour:Minute Format
format = '[[  $time ](fg:#a0a9cb)]($style)'

[character]
success_symbol = '[ ](bold green) '
error_symbol = '[ ](#E84D44) '
vimcmd_symbol = '[󰕷 ](bold green) '

[palettes.tokyonight_night]
red = "#f7768e"
orange = "#ff9e64"
yellow = "#e0af68"
light-green = "#9ece6a"
green = "#73daca"
turquoise = "#89ddff"
light-cyan = "#b4f9f8"
teal = "#2ac3de"
cyan = "#7dcfff"
blue = "#7aa2f7"
magenta = "#bb9af7"
white = "#c0caf5"
light-gray = "#9aa5ce"
parameters = "#cfc9c2"
comment = "#565f89"
black = "#414868"
foreground = "#a9b1d6"
foreground_highlight = "#c0caf5"
foreground_gutter = "#363b54"
background = "#1a1b26"
background_highlight = "#30374b"
background_menu = "#16161e"
