# This will show the time on a 2nd line
# Add a "\" at the end of an item, if you want the next item to show on the same line
format = """
$username\
$directory\
$nodejs\
$character\
"""

[character]
success_symbol = '[  ](#fdf2bb bold) '
error_symbol = '[  ](#f62d14 bold) '
vicmd_symbol = '[󰕷  ](#fbe260 bold) '

[directory]
style = " bold"
disabled = false
truncation_length = 3
truncation_symbol = "…/"

[battery]
disabled = true

[gcloud]
disabled = true

[username]
style_user = '#fad61d bold'
style_root = 'white bold'
format = '[$user]($style).@.'
show_always = true

[nodejs]
symbol = " "
format = '[[$symbol($version)](#fdf2bb)]($style) '

