-- require("items.widgets.weather")
require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.wifi")
require("items.widgets.cpu")
require("items.widgets.ram")
-- require("items.widgets.ssd")
