console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[transient_prompt]
background = "transparent"
template = '❯ '
foreground_templates = [
	'{{if gt .Code 0}}#f7768e{{end}}',
	'{{if eq .Code 0}}#9ece6a{{end}}',
]

[secondary_prompt]
background = "transparent"
foreground = "#c0caf5"
template = "╰─❯ "

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

[[blocks.segments]]
foreground = "#c0caf5"
style = "plain"
template = "<#c0caf5>╭─(<><#7aa2f7>{{ .Path }}</><#c0caf5>)"
type = "path"

[blocks.segments.properties]
style = "full"

[[blocks.segments]]
foreground = "#EBCB8B"
style = "plain"
template = "<#ff9e64> - (</>{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }}{{ else }}{{ end }} {{ .Full }}<#81A1C1>)</>"
type = "node"

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
template = '{{ .FormattedMs }}'
foreground = '#ef9e64'
background = 'transparent'
type = 'executiontime'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
threshold = 50

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
foreground = "#c0caf5"
style = "plain"
template = "╰─"
type = "text"

[[blocks.segments]]
template = "<#c0caf5>(</>{{ if .Env.POSH_VI_MODE }}{{ .Env.POSH_VI_MODE }}{{ end }}<#c0caf5>)</>"
background = 'transparent'
type = 'text'
style = 'plain'

[[blocks.segments]]
template = '❯'
background = 'transparent'
foreground = '#ef9e64'
foreground_templates = [
	'{{if gt .Code 0}}#f7768e{{end}}',
	'{{if eq .Code 0}}#9ece6a{{end}}',
]
type = 'text'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
