console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
template = ' '
foreground = 'magenta'
background = 'transparent'

[transient_prompt]
template = ' '
background = 'transparent'
foreground_templates = [
  '{{if gt .Code 0}}#f7768e{{end}}',
  '{{if eq .Code 0}}#9d7cd8{{end}}',
]

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

[[blocks.segments]]
background = "#9ece6a"
foreground = "#1a1b26"
leading_diamond = "░▒▓"
trailing_diamond = ""
style = "diamond"
template = " {{ .Path }} "
type = "path"

[blocks.segments.properties]
style = "full"

[[blocks.segments]]
background = "#e0af68"
foreground = "#1a1b26"
style = "diamond"
trailing_diamond = ""
template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }}{{ else }}{{ end }} {{ .Full }}'
type = "node"

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
template = '{{ .FormattedMs }}'
foreground = '#e0af68'
background = 'transparent'
type = 'executiontime'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
threshold = 50

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = ' '
background = 'transparent'
type = 'text'
style = 'plain'
foreground_templates = [
  '{{if gt .Code 0}}#f7768e{{end}}',
  '{{if eq .Code 0}}#9d7cd8{{end}}',
]

[blocks.segments.properties]
cache_duration = 'none'
