console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[transient_prompt]
background = "transparent"
template = '❯ '
foreground_templates = [
  '{{if gt .Code 0}}#BF616A{{end}}',
  '{{if eq .Code 0}}#88C0D0{{end}}',
]

[secondary_prompt]
background = "transparent"
foreground = "#D8DEE9"
template = "╰─❯ "

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

[[blocks.segments]]
foreground = "#A3BE8C"
style = "plain"
template = "<#81A1C1>╭─(</>{{ .Path }}<#81A1C1>)</>"
type = "path"

[blocks.segments.properties]
style = "full"

[[blocks.segments]]
foreground = "#EBCB8B"
style = "plain"
template = "<#81A1C1> - (</>{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }}{{ else }}{{ end }} {{ .Full }}<#81A1C1>)</>"
type = "node"

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
template = '{{ .FormattedMs }}'
foreground = '#EBCB8B'
background = 'transparent'
type = 'executiontime'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
threshold = 50

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
foreground = "#81A1C1"
style = "plain"
template = "╰─"
type = "text"

[[blocks.segments]]
template = "<#81A1C1>(</>{{ if .Env.POSH_VI_MODE }}{{ .Env.POSH_VI_MODE }}{{ end }}<#81A1C1>)─</>"
background = 'transparent'
type = 'text'
style = 'plain'

[[blocks.segments]]
template = '❯'
background = 'transparent'
foreground_templates = [
  '{{if gt .Code 0}}#BF616A{{end}}',
  '{{if eq .Code 0}}#88C0D0{{end}}',
]
type = 'text'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
