console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[transient_prompt]
background = "transparent"
template = '❯ '
foreground_templates = [
  '{{if gt .Code 0}}#f7768e{{end}}',
  '{{if eq .Code 0}}#9d7cd8{{end}}',
]

[secondary_prompt]
background = "transparent"
foreground = "#c0caf5"
template = "╰─❯ "

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

[[blocks.segments]]
foreground = "#9ece6a"
style = "plain"
template = "<#565f89>╭─(</>{{ .Path }}<#565f89>)</>"
type = "path"

[blocks.segments.properties]
style = "full"

[[blocks.segments]]
foreground = "#e0af68"
style = "plain"
template = "<#565f89> - (</>{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }}{{ else }}{{ end }} {{ .Full }}<#565f89>)</>"
type = "node"

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
template = '{{ .FormattedMs }}'
foreground = '#e0af68'
background = 'transparent'
type = 'executiontime'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
threshold = 50

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
foreground = "#565f89"
style = "plain"
template = "╰─"
type = "text"

[[blocks.segments]]
template = "<#565f89>(</>{{ if .Env.POSH_VI_MODE }}{{ .Env.POSH_VI_MODE }}{{ end }}<#565f89>)─</>"
background = 'transparent'
type = 'text'
style = 'plain'

[[blocks.segments]]
template = '❯'
background = 'transparent'
foreground_templates = [
  '{{if gt .Code 0}}#f7768e{{end}}',
  '{{if eq .Code 0}}#9d7cd8{{end}}',
]
type = 'text'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
